### Edit this file to your liking

CONFIG = \
    {
        'API_ID': 0,  # Telegram Api ID
        'API_HASH': 'your_ap1_hash',  # Telegram Api ID
        'TOKEN': 'your_bot_t0k3n',  # Bot token
        'SESSION_NAME': 'Bugs_Bunny',  # The name of the session file generated by telethon.
        'ALLOWED_CHATS': [0, 0, 0],  # Chats to allow your bot to be in
        'SUGGESTIONS_BUGS_CHAT': [0],  # The chat where the bugs or suggestion made are forwarded!
        'DISPENSER_HOOK': '',
        # The Dispenser hook for Aurora Store email generation. [You shouldn't need this as it's made specially for the AuroraOSS groups.
        'NIGHTLY_URL': '',
        # The link to the aurora nightlies [It should work if your website has the same layout as https://auroraoss.com/AuroraStore/Nightly/ and if you set the right NIGHTLY_NAME_MATCH config below to match the apks path from your website found on the get request response text.
        'NIGHTLY_NAME_MATCH': r'',
        # The regex used to match the nightlies versions at https://auroraoss.com/AuroraStore/Nightly/.
        'NIGHTLY_ALGO': max  # The algorithm function used to pick the nightly [Here I use the builtin max funcion.
    }

# 'Use config = Config(debug=True) in init to use these config values!'
DEBUG_CONFIG = \
    {
        'API_ID': 0,  # Telegram Api ID
        'API_HASH': 'your_ap1_hash',  # Telegram Api ID
        'TOKEN': 'your_bot_t0k3n',  # Bot token
        'SESSION_NAME': 'Bugs_Bunny',  # The name of the session file generated by telethon.
        'ALLOWED_CHATS': [0, 0, 0],  # Chats to allow your bot to be in
        'SUGGESTIONS_BUGS_CHAT': [0],  # The chat where the bugs or suggestion made are forwarded!
        'DISPENSER_HOOK': '',
        # The Dispenser hook for Aurora Store email generation. [You shouldn't need this as it's made specially for the AuroraOSS groups.
        'NIGHTLY_URL': '',
        # The link to the aurora nightlies [It should work if your website has the same layout as https://auroraoss.com/AuroraStore/Nightly/ and if you set the right NIGHTLY_NAME_MATCH config below to match the apks path from your website found on the get request response text.
        'NIGHTLY_NAME_MATCH': r'',
        # The regex used to match the nightlies versions at https://auroraoss.com/AuroraStore/Nightly/.
        'NIGHTLY_ALGO': max  # The algorithm function used to pick the nightly [Here I use the builtin max funcion.
    }


class Config(object):
    def __init__(self, debug=False):
        if debug:
            self._config = DEBUG_CONFIG
        else:
            self._config = CONFIG

    def get_property(self, property_name, default=None):
        if property_name not in self._config.keys():
            return default
        return self._config[property_name]
